### PR TITLE
Fix OPA Metadata parameters validation (fix #293)

### LINKED ISSUE #293: Legacy parameters warning is generated even for new style parameters
Warning `Parameters are set with legacy annotations, this functionality will be removed in a future release. Please migrate to OPA Metadata annotations` is printed even when using new style parameters.

headerParams are set from rich annotations too:
https://github.com/plexsystems/konstraint/blob/67f9689ae1f0d5599a5e0015a216aa9fe1f893c1/internal/rego/rego.go#L536-L539
https://github.com/plexsystems/konstraint/blob/67f9689ae1f0d5599a5e0015a216aa9fe1f893c1/internal/rego/rego.go#L570

which causes `create` to believe there are legacy defined parameters present:
https://github.com/plexsystems/konstraint/blob/67f9689ae1f0d5599a5e0015a216aa9fe1f893c1/internal/rego/rego.go#L141-L144
https://github.com/plexsystems/konstraint/blob/67f9689ae1f0d5599a5e0015a216aa9fe1f893c1/internal/commands/create.go#L181-L182

### PR DESCRIPTION
**Pull request by stek29**
I've also removed what seems to be a duplicating parameters checking code: if I understood the code correctly, `paramDiff` check is enough and `for _, bodyParam := range bodyParams` would never be reached.

### CODE REVIEW

File: internal/rego/rego.go [hunk 1]
```diff
@@ -533,33 +533,22 @@ func parseDirectory(directory string, parseImports bool) ([]Rego, error) {
...
-				if headerParam.Name == bodyParam {
-					seen = true
-					break
-				}
-			}
-
-			if !seen {
-				return nil, fmt.Errorf("missing @parameter tag for parameter: %s", bodyParam)
-			}
+			return nil, fmt.Errorf("missing definitions for parameters %v found in the policy: %v", paramsDiff, file.Name)
```
Comment (jalseth) [inline internal/rego/rego.go:551]: nit: `%s` should be used for `file.Name`

**Review by jalseth — APPROVED** [review]
LGTM. Thanks for catching this!
